FROM debian:bookworm-slim

RUN \
  apt-get update && \
  apt-get -y install ca-certificates tini && \
  apt-get clean

RUN groupadd -r caido && useradd --no-log-init -m -r -g caido caido

COPY caido-cli /usr/bin/caido-cli

USER caido

EXPOSE 8080

ENTRYPOINT ["tini", "--"]
CMD ["caido-cli", "--no-renderer-sandbox", "--no-open", "--listen", "0.0.0.0:8080"]
