name: Update APT Repository

on:
  schedule:
    # Run daily at 6:00 AM UTC
    - cron: "0 6 * * *"
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "scripts/**"
      - "aptify.yml"
      - "package.json"
      - "bun.lockb"
      - ".github/workflows/update-apt-repo.yml"

jobs:
  update-repo:
    name: Update APT Repository
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write # Ensure GITHUB_TOKEN has write permissions

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: "Download and install aptify"
        run: |
          wget https://github.com/dpeckett/aptify/releases/download/v0.8.0/aptify_0.8.0-1_amd64.deb
          sudo apt install -y ./aptify_0.8.0-1_amd64.deb

      - name: "Verify Dependencies"
        run: bun run verify-deps

      - name: Configure aptify GPG Key
        run: |
          mkdir -p "$XDG_CONFIG_HOME/aptify"
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > "$XDG_CONFIG_HOME/aptify/aptify_private.asc"

      - name: Run Tests and Quality Checks
        run: bun run test:all

      - name: Update APT Repository
        run: |
          echo "Starting APT repository update process..."
          bun run repo:update

      - name: Ensure repo directory exists
        run: mkdir -p repo

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo
          keep_files: false
          enable_jekyll: false
          commit_message: "Update APT repository - ${{ github.sha }}"
          publish_branch: gh-pages
